[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  VITE_DEV_MODE = "false"

[context.deploy-preview.environment]
  VITE_DEV_MODE = "true"

[context.branch-deploy.environment]
  VITE_DEV_MODE = "true"
